#!/usr/bin/env python3
"""
FXM Elite Predict - Scraper Integration Script
Automatically generates HTML files from SofaScore prediction data
Compatible with GitHub Pages and static hosting
"""

import json
import os
from datetime import datetime
from pathlib import Path

class PredictionScraper:
    """
    Handles scraping and processing of SofaScore prediction data
    Generates static HTML files for the website
    """
    
    def __init__(self, output_dir="website"):
        self.output_dir = output_dir
        self.predictions = []
        self.results = []
        
    def load_predictions_from_json(self, json_file):
        """Load predictions from JSON file generated by sofascore_scraper.py"""
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
                self.predictions = data.get('predictions', [])
                self.results = data.get('results', [])
                print(f"✓ Loaded {len(self.predictions)} predictions from {json_file}")
        except FileNotFoundError:
            print(f"✗ File not found: {json_file}")
            return False
        return True
    
    def generate_prediction_card(self, pred):
        """Generate HTML card for a single prediction"""
        confidence = pred.get('confidence', 0)
        sport = pred.get('sport', 'Unknown').lower()
        
        # Determine badge color based on confidence
        if confidence >= 80:
            confidence_class = 'badge-confidence'
        else:
            confidence_class = 'badge-confidence'
        
        card_html = f"""
                <div class="prediction-card" data-sport="{sport}" data-confidence="{confidence}" data-type="{pred.get('type', '').lower()}" data-league="{pred.get('league', '').lower()}">
                    <div class="card-header">
                        <div class="badges">
                            <span class="badge badge-sport"><i class="fas fa-{self.get_sport_icon(sport)}"></i> {pred.get('sport', 'Unknown')} - {pred.get('league', 'League')}</span>
                            <span class="badge {confidence_class}">{confidence}% Confidence</span>
                            <span class="badge badge-type">{pred.get('type', 'Unknown')}</span>
                        </div>
                    </div>
                    <div class="match-time">
                        <i class="fas fa-calendar"></i> {pred.get('match_time', 'TBD')}
                    </div>
                    <div class="match-info">
                        <div class="teams-container">
                            <span class="team">{pred.get('team1', 'Team 1')}</span>
                            <span class="vs">vs</span>
                            <span class="team away">{pred.get('team2', 'Team 2')}</span>
                        </div>
                        <div class="league">{pred.get('league', 'League')} - {pred.get('event', 'Event')}</div>
                    </div>
                    <div class="prediction-details">
                        <div class="prediction-type">Prediction</div>
                        <div class="prediction-value">{pred.get('prediction', 'TBD')}</div>
                        <div class="odds">Odds: {pred.get('odds', 'N/A')} | ROI: {pred.get('roi', 'N/A')}</div>
                    </div>
                    <div class="card-footer">
                        <div class="consensus">
                            <span>Community:</span>
                            <div class="consensus-bar">
                                <div class="consensus-fill" style="width: {confidence}%"></div>
                            </div>
                            <span>{confidence}%</span>
                        </div>
                        <button class="btn-small">Details</button>
                    </div>
                </div>
        """
        return card_html
    
    def generate_result_row(self, result):
        """Generate HTML table row for a result"""
        result_class = 'result-win' if result.get('result') == 'WIN' else ('result-push' if result.get('result') == 'PUSH' else 'result-loss')
        result_symbol = '✓' if result.get('result') == 'WIN' else ('=' if result.get('result') == 'PUSH' else '✗')
        
        row_html = f"""
                    <tr>
                        <td>{result.get('date', 'N/A')}</td>
                        <td><span class="sport-badge">{result.get('sport', 'Unknown')}</span></td>
                        <td>{result.get('match', 'N/A')}</td>
                        <td>{result.get('prediction', 'N/A')}</td>
                        <td><span class="confidence-badge">{result.get('confidence', 0)}%</span></td>
                        <td>{result.get('odds', 'N/A')}</td>
                        <td><span class="{result_class}">{result_symbol} {result.get('result', 'PENDING')}</span></td>
                        <td>{result.get('roi', 'N/A')}</td>
                    </tr>
        """
        return row_html
    
    def get_sport_icon(self, sport):
        """Get Font Awesome icon name for sport"""
        icons = {
            'tennis': 'tennis',
            'football': 'futbol',
            'basketball': 'basketball',
            'hockey': 'hockey-puck',
            'baseball': 'baseball',
            'american football': 'football'
        }
        return icons.get(sport.lower(), 'chart-line')
    
    def generate_predictions_page(self):
        """Generate predictions.html with live data"""
        if not self.predictions:
            print("⚠ No predictions to generate")
            return False
        
        cards_html = ''.join([self.generate_prediction_card(p) for p in self.predictions[:12]])
        
        # Read template and inject data
        template_path = Path(__file__).parent / 'predictions.html'
        if not template_path.exists():
            print(f"✗ Template not found: {template_path}")
            return False
        
        with open(template_path, 'r') as f:
            content = f.read()
        
        # Replace placeholder with actual predictions
        content = content.replace(
            '<!-- PREDICTIONS_PLACEHOLDER -->',
            cards_html
        )
        
        output_path = Path(self.output_dir) / 'predictions.html'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        print(f"✓ Generated predictions page: {output_path}")
        return True
    
    def generate_results_page(self):
        """Generate results.html with historical data"""
        if not self.results:
            print("⚠ No results to generate")
            return False
        
        rows_html = ''.join([self.generate_result_row(r) for r in self.results[:20]])
        
        # Read template and inject data
        template_path = Path(__file__).parent / 'results.html'
        if not template_path.exists():
            print(f"✗ Template not found: {template_path}")
            return False
        
        with open(template_path, 'r') as f:
            content = f.read()
        
        # Replace placeholder with actual results
        content = content.replace(
            '<!-- RESULTS_PLACEHOLDER -->',
            rows_html
        )
        
        output_path = Path(self.output_dir) / 'results.html'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        print(f"✓ Generated results page: {output_path}")
        return True
    
    def generate_stats_json(self):
        """Generate statistics JSON for dashboard"""
        total_predictions = len(self.predictions)
        total_results = len(self.results)
        wins = sum(1 for r in self.results if r.get('result') == 'WIN')
        losses = sum(1 for r in self.results if r.get('result') == 'LOSS')
        pushes = sum(1 for r in self.results if r.get('result') == 'PUSH')
        
        accuracy = (wins / total_results * 100) if total_results > 0 else 0
        
        stats = {
            'generated_at': datetime.now().isoformat(),
            'total_predictions': total_predictions,
            'total_results': total_results,
            'wins': wins,
            'losses': losses,
            'pushes': pushes,
            'accuracy_percentage': round(accuracy, 1),
            'roi_total': sum(float(r.get('roi', '0').rstrip('%')) for r in self.results if r.get('roi'))
        }
        
        output_path = Path(self.output_dir) / 'stats.json'
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w') as f:
            json.dump(stats, f, indent=2)
        
        print(f"✓ Generated statistics: {output_path}")
        return True
    
    def copy_static_files(self):
        """Copy static HTML files to output directory"""
        static_files = ['index.html', 'about.html', 'contact.html', 'faq.html']
        output_dir = Path(self.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        for file in static_files:
            src = Path(__file__).parent / file
            dst = output_dir / file
            
            if src.exists():
                with open(src, 'r') as f:
                    content = f.read()
                with open(dst, 'w') as f:
                    f.write(content)
                print(f"✓ Copied {file}")
            else:
                print(f"⚠ File not found: {file}")
    
    def build_website(self, predictions_json='predictions.json'):
        """Build complete website from data"""
        print("\n" + "="*50)
        print("FXM Elite Predict - Website Builder")
        print("="*50 + "\n")
        
        # Load data
        if not self.load_predictions_from_json(predictions_json):
            print("Using sample data...")
            self.predictions = self._get_sample_predictions()
            self.results = self._get_sample_results()
        
        # Copy static files
        self.copy_static_files()
        
        # Generate dynamic pages
        self.generate_predictions_page()
        self.generate_results_page()
        self.generate_stats_json()
        
        print("\n" + "="*50)
        print("✓ Website built successfully!")
        print(f"Output directory: {self.output_dir}")
        print("="*50 + "\n")
    
    @staticmethod
    def _get_sample_predictions():
        """Get sample predictions for testing"""
        return [
            {
                'sport': 'Tennis',
                'league': 'ATP',
                'team1': 'Jannik Sinner',
                'team2': 'Daniil Medvedev',
                'match_time': '2026-02-15 14:00 UTC',
                'event': 'ATP Masters 1000 - Dubai',
                'prediction': 'Sinner Win',
                'confidence': 82,
                'odds': 1.85,
                'roi': '+12.3%',
                'type': 'Match Winner'
            },
            {
                'sport': 'Football',
                'league': 'Premier League',
                'team1': 'Manchester City',
                'team2': 'Liverpool',
                'match_time': '2026-02-15 15:30 UTC',
                'event': 'Matchday 24',
                'prediction': 'Over 2.5 Goals',
                'confidence': 78,
                'odds': 1.72,
                'roi': '+8.5%',
                'type': 'Over/Under'
            }
        ]
    
    @staticmethod
    def _get_sample_results():
        """Get sample results for testing"""
        return [
            {
                'date': '2026-02-14',
                'sport': 'Tennis',
                'match': 'Sinner vs Medvedev',
                'prediction': 'Sinner Win',
                'confidence': 82,
                'odds': 1.85,
                'result': 'WIN',
                'roi': '+12.3%'
            },
            {
                'date': '2026-02-14',
                'sport': 'Football',
                'match': 'Man City vs Liverpool',
                'prediction': 'Over 2.5 Goals',
                'confidence': 78,
                'odds': 1.72,
                'result': 'WIN',
                'roi': '+8.5%'
            }
        ]


if __name__ == '__main__':
    # Initialize scraper
    scraper = PredictionScraper(output_dir='website')
    
    # Build website
    scraper.build_website('predictions.json')
